"""
Telegram Bet Signal Notifier — Bot API + Telethon fallback

PRIMARY: Bot API (your BotFather bot)
  - Uses HTTP POST to api.telegram.org — no session needed
  - Requires: TELEGRAM_BOT_TOKEN + TELEGRAM_BOT_CHAT_ID
  - Zero latency: single HTTPS call per message (~100-200ms)
  - HOW TO GET CHAT_ID:
      1. Open Telegram, search your bot name, send /start
      2. Open: https://api.telegram.org/bot{YOUR_TOKEN}/getUpdates
      3. Find "chat":{"id": 123456789} — that number is your CHAT_ID

FALLBACK: Telethon StringSession (sends to Saved Messages)
  - Used if BOT_TOKEN or CHAT_ID is missing
  - Requires TELEGRAM_SESSION (generated by tg_step2_login.py)

All signal types:
  BET CALL | BOOKSET | STOP LOSS | LOSS CUT | SESSION | BOOKMAKER EDGE
  ANTI-PANIC (HOLD/EXIT) | MATCH STARTED | DAILY SUMMARY | INFO
"""
import asyncio
import logging
import httpx
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

# ── Bot API sender (primary) ─────────────────────────────────────────────────
_bot_token: str = ""
_bot_chat_id: str = ""
_bot_ready: bool = False

# ── Telethon fallback ─────────────────────────────────────────────────────────
_tele_client = None
_tele_ready  = False
_tele_init_attempted = False


async def init_notifier():
    """
    Call ONCE at startup (from main.py lifespan).
    Sets up Bot API sender and/or Telethon fallback.
    """
    global _bot_token, _bot_chat_id, _bot_ready
    global _tele_client, _tele_ready, _tele_init_attempted

    try:
        from config.settings import settings

        # ── Bot API setup (preferred) ──────────────────────────────────────
        token   = getattr(settings, "TELEGRAM_BOT_TOKEN", "")
        chat_id = getattr(settings, "TELEGRAM_BOT_CHAT_ID", "") or \
                  getattr(settings, "TELEGRAM_ALERT_CHAT_ID", "")

        if token and chat_id:
            # Verify the bot + chat_id work
            async with httpx.AsyncClient(timeout=10) as client:
                r = await client.get(
                    f"https://api.telegram.org/bot{token}/getMe"
                )
                if r.status_code == 200:
                    bot_name = r.json().get("result", {}).get("username", "?")
                    _bot_token   = token
                    _bot_chat_id = str(chat_id)
                    _bot_ready   = True
                    logger.info(f"Telegram Bot API ready — @{bot_name} → chat {chat_id}")
                else:
                    logger.warning(f"Telegram Bot API error: {r.status_code} {r.text[:100]}")
        else:
            logger.info(
                "Telegram Bot API: BOT_TOKEN or BOT_CHAT_ID missing.\n"
                "  HOW TO FIX:\n"
                "  1. Create a bot via @BotFather → get token\n"
                "  2. Send /start to your bot in Telegram\n"
                "  3. Open https://api.telegram.org/bot{TOKEN}/getUpdates to get your chat_id\n"
                "  4. Set TELEGRAM_BOT_TOKEN and TELEGRAM_BOT_CHAT_ID in .env"
            )

        # ── Telethon fallback ──────────────────────────────────────────────
        if not _bot_ready and not _tele_init_attempted:
            _tele_init_attempted = True
            session_str = getattr(settings, "TELEGRAM_SESSION", "")
            api_id      = getattr(settings, "TELEGRAM_API_ID", "")
            api_hash    = getattr(settings, "TELEGRAM_API_HASH", "")

            if session_str and api_id and api_hash:
                from telethon import TelegramClient
                from telethon.sessions import StringSession
                _tele_client = TelegramClient(
                    StringSession(session_str),
                    int(api_id),
                    api_hash,
                    connection_retries=5,
                    retry_delay=1,
                    auto_reconnect=True,
                )
                await _tele_client.connect()
                if await _tele_client.is_user_authorized():
                    _tele_ready = True
                    logger.info("Telegram Telethon fallback ready (Saved Messages)")
                    asyncio.create_task(_keepalive_loop())
                else:
                    logger.warning("Telegram Telethon: not authorized — run tg_step1/tg_step2 scripts")

    except Exception as e:
        logger.error(f"Telegram notifier init error: {e}")


async def _keepalive_loop():
    """Keep Telethon connection alive with 60s pings."""
    global _tele_client, _tele_ready
    while True:
        await asyncio.sleep(60)
        if _tele_client and _tele_ready:
            try:
                await _tele_client.get_me()
            except Exception as e:
                logger.warning(f"Telegram keepalive failed: {e}")
                _tele_ready = False
                try:
                    await _tele_client.connect()
                    if await _tele_client.is_user_authorized():
                        _tele_ready = True
                except Exception:
                    pass


async def send_signal(message: str):
    """
    Send a message via Bot API (primary) or Telethon (fallback).
    Caller should await directly for zero delay on critical signals.
    """
    global _bot_ready, _tele_ready

    # ── Try Bot API first ──────────────────────────────────────────────────
    if _bot_ready:
        try:
            async with httpx.AsyncClient(timeout=8) as client:
                r = await client.post(
                    f"https://api.telegram.org/bot{_bot_token}/sendMessage",
                    json={
                        "chat_id":    _bot_chat_id,
                        "text":       message,
                        "parse_mode": "Markdown",
                    },
                )
                if r.status_code == 200:
                    return  # success
                # Rate limited (429) — log and fall through to Telethon
                logger.warning(f"Bot API error {r.status_code}: {r.text[:120]}")
        except Exception as e:
            logger.error(f"Bot API send error: {e}")

    # ── Telethon fallback ──────────────────────────────────────────────────
    if not _tele_ready:
        await init_notifier()

    if _tele_ready and _tele_client:
        try:
            await _tele_client.send_message("me", message, parse_mode="md")
        except Exception as e:
            logger.error(f"Telethon send error: {e}")
            return

    if not _bot_ready and not _tele_ready:
        logger.debug(f"Telegram not configured — skipped: {message[:60]}")


# ── Signal formatters ────────────────────────────────────────────────────────

def _flag(tier: str) -> str:
    return {"scalp": "⚡", "mid": "📈", "high": "🚀", "very_high": "🎯"}.get(tier, "📌")


async def send_bet_call(
    action: str,
    team: str,
    odds: float,
    stake: float,
    ev: float,
    confidence: float,
    reasoning: str,
    overs: float,
    score: str,
    bookset_at: float,
    stop_loss: float,
    tier: str = "mid",
    match: str = "",
    ai_source: str = "",
):
    action_emoji = {"BACK": "🟢 BACK", "LAY": "🔴 LAY", "PROGRESSIVE_BOOKSET": "🔒 BOOKSET"}.get(action, action)
    ts     = datetime.now().strftime("%H:%M:%S IST")
    ai_tag = f" 🧠 GEMINI" if ai_source == "gemini" else ""

    msg = (
        f"{_flag(tier)} *BET CALL{ai_tag} — {match or 'IPL'}*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"*{action_emoji} {team} @ {odds:.2f}*\n"
        f"💰 Stake: ₹{stake:.0f}  |  EV: +{ev*100:.1f}%\n"
        f"🎯 Confidence: {confidence*100:.0f}%\n"
        f"📊 Overs: {overs:.1f}  |  Score: {score}\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        + (f"📍 Bookset target: *{bookset_at:.2f}*\n" if bookset_at else "")
        + (f"🛑 Stop loss at: *{stop_loss:.2f}*\n" if stop_loss else "")
        + f"💬 _{reasoning[:160]}_\n"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_bookset_call(
    team: str,
    entry_odds: float,
    current_odds: float,
    overs: float,
    match: str = "",
    stake_a: float = 0,
    stake_b: float = 0,
    guaranteed_profit: float = 0,
):
    ts          = datetime.now().strftime("%H:%M:%S IST")
    compression = (current_odds / entry_odds * 100) if entry_odds > 0 else 0
    profit_line = f"*Guaranteed profit: ₹{guaranteed_profit:.0f}*\n" if guaranteed_profit else ""
    lay_line    = f"LAY {team} ₹{stake_a:.0f} @ {current_odds:.2f}\n" if stake_a else f"LAY {team} now\n"

    msg = (
        f"🔒 *BOOKSET NOW — {match or 'IPL'}*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"Backed *{team}* @ {entry_odds:.2f}\n"
        f"Now trading @ *{current_odds:.2f}* ({compression:.0f}% of entry)\n"
        f"📊 Overs: {overs:.1f}\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"{lay_line}"
        f"{profit_line}"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_stop_loss(
    team: str,
    entry_odds: float,
    current_odds: float,
    loss_pct: float,
    hedge_team: str,
    hedge_stake: float,
    overs: float,
    score: str,
    match: str = "",
):
    ts = datetime.now().strftime("%H:%M:%S IST")
    msg = (
        f"🛑 *STOP LOSS TRIGGERED — {match or 'IPL'}*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"Backed *{team}* @ {entry_odds:.2f}\n"
        f"Now @ *{current_odds:.2f}* — loss {loss_pct:.1f}%\n"
        f"📊 Overs: {overs:.1f} | Score: {score}\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"*HEDGE: BACK {hedge_team} ₹{hedge_stake:.0f}* to cut losses\n"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_loss_cut(
    team: str,
    entry_odds: float,
    current_odds: float,
    pnl: float,
    match: str = "",
):
    ts    = datetime.now().strftime("%H:%M:%S IST")
    emoji = "💚" if pnl >= 0 else "💔"
    msg   = (
        f"{emoji} *LOSS CUT EXECUTED — {match or 'IPL'}*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"*{team}* entry @ {entry_odds:.2f} → exit @ {current_odds:.2f}\n"
        f"P&L: *₹{pnl:+.0f}*\n"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_session_call(
    label: str,
    side: str,
    stake: float,
    confidence: float,
    reasoning: str,
    overs: float,
    score: str,
    match: str = "",
    predicted_runs: float = 0,
    prob_over: float = 0,
    prob_under: float = 0,
):
    ts         = datetime.now().strftime("%H:%M:%S IST")
    side_emoji = "🔼 YES (OVER)" if side.upper() in ("YES", "OVER") else "🔽 NO (UNDER)"
    stats_line = f"📈 P(OVER): {prob_over:.0%} | P(UNDER): {prob_under:.0%}\n" if prob_over else ""
    pred_line  = f"🎯 Model predicts: {predicted_runs:.0f} runs\n" if predicted_runs else ""

    msg = (
        f"📊 *SESSION CALL — {match or 'IPL'}*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"*{side_emoji} {label}*\n"
        f"💰 Stake: ₹{stake:.0f}  |  Confidence: {confidence*100:.0f}%\n"
        f"📊 Overs: {overs:.1f}  |  Score: {score}\n"
        f"{pred_line}"
        f"{stats_line}"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"💬 _{reasoning[:160]}_\n"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_bookmaker_call(
    team: str,
    bookmaker_odds: float,
    match_odds: float,
    edge: float,
    stake: float,
    overs: float,
    score: str,
    match: str = "",
):
    """Alert when bookmaker price offers edge vs match odds."""
    ts     = datetime.now().strftime("%H:%M:%S IST")
    action = "🟢 BACK" if bookmaker_odds < match_odds else "🔴 LAY"
    msg    = (
        f"📋 *BOOKMAKER EDGE — {match or 'IPL'}*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"*{action} {team}*\n"
        f"Bookmaker: {bookmaker_odds:.2f}  |  Match Odds: {match_odds:.2f}\n"
        f"Edge: *{edge*100:.1f}%* | Stake: ₹{stake:.0f}\n"
        f"📊 Overs: {overs:.1f}  |  Score: {score}\n"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_anti_panic(
    signal: str,
    team: str,
    overs: float,
    score: str,
    match: str = "",
    reasoning: str = "",
):
    ts          = datetime.now().strftime("%H:%M:%S IST")
    reason_line = f"💬 _{reasoning[:120]}_\n" if reasoning else ""
    if signal == "HOLD":
        msg = (
            f"😤 *WICKET — HOLD POSITION — {match or 'IPL'}*\n"
            f"━━━━━━━━━━━━━━━━━━━\n"
            f"Wicket fell but *recoverable situation*.\n"
            f"*{team}* — Overs: {overs:.1f} | Score: {score}\n"
            f"{reason_line}"
            f"*Do NOT panic exit. Hold your position.*\n"
            f"⏰ {ts}"
        )
    else:
        msg = (
            f"🚨 *WICKET — EXIT NOW — {match or 'IPL'}*\n"
            f"━━━━━━━━━━━━━━━━━━━\n"
            f"Collapse confirmed. Cut losses immediately.\n"
            f"*{team}* — Overs: {overs:.1f} | Score: {score}\n"
            f"{reason_line}"
            f"*LAY your position NOW.*\n"
            f"⏰ {ts}"
        )
    await send_signal(msg)


async def send_match_started(
    team_a: str,
    team_b: str,
    odds_a: float,
    odds_b: float,
    venue: str = "",
):
    ts         = datetime.now().strftime("%H:%M:%S IST")
    venue_line = f"🏟️ Venue: {venue}\n" if venue else ""
    msg        = (
        f"🏏 *MATCH DETECTED — Live on RoyalBook*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"*{team_a}* @ {odds_a:.2f}  vs  *{team_b}* @ {odds_b:.2f}\n"
        f"{venue_line}"
        f"🤖 Gemini analyst online — signals incoming...\n"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_daily_summary(
    total_pnl: float,
    trades: int,
    win_rate: float,
    bankroll: float,
    match: str = "",
):
    ts    = datetime.now().strftime("%H:%M IST")
    emoji = "📈" if total_pnl >= 0 else "📉"
    msg   = (
        f"{emoji} *DAILY SUMMARY — {match or 'IPL'}*\n"
        f"━━━━━━━━━━━━━━━━━━━\n"
        f"P&L: *₹{total_pnl:+.0f}*\n"
        f"Trades: {trades}  |  Win Rate: {win_rate:.0%}\n"
        f"Bankroll: ₹{bankroll:.0f}\n"
        f"⏰ {ts}"
    )
    await send_signal(msg)


async def send_info(text: str):
    await send_signal(f"ℹ️ {text}")
